# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Hello, world2!
    echo "this is my $(Build.ArtifactStagingDirectory) test for bin" > $(Build.ArtifactStagingDirectory)/bin_log.txt
    echo "this is my $(Build.ArtifactStagingDirectory) test for bin" > $(Build.ArtifactStagingDirectory)/bin_log1.txt
    echo "this is my $(Build.ArtifactStagingDirectory) test for bin" > $(Build.ArtifactStagingDirectory)/bin_log2.txt
    echo "this is my $(Build.ArtifactStagingDirectory) test for bin" > $(Build.ArtifactStagingDirectory)/bin_log3.txt
    echo "this is my $(Build.ArtifactStagingDirectory) test for bin" > $(Build.ArtifactStagingDirectory)/bin_log4.txt
  displayName: 'Run a one-line script2'

- script: echo Hello, world!
  displayName: 'Run a one-line script22'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
